### ISSUE TITLE
Home Assistant connection

### ISSUE THREAD

**Issue by FlexxFR** [SecurAir/SecurAir#1]
1. make sure MQTT is running, including username/password
2. Install visual studio code add-on (needed for each configuration of the configuration.yaml 
3. manual add this

Put this in configuration.yaml

```
mqtt:
  sensor:
    - name: "securair_co2"
      state_topic: "securair01-co2"
      value_template: "{{value_json.value}}"
      unit_of_measurement: "ppm"
    - name: "securair_temperature"
      state_topic: "securair01-temp"
      value_template: "{{value_json.value}}"
      unit_of_measurement: "°C"
    - name: "securair_humidity"
      state_topic: "securair01-hum"
      value_template: "{{value_json.value}}"
      unit_of_measurement: "%"
```

Explanation
    - name: "securair_co2"      <--- name in home asssistant
      state_topic: "securair01-co2"  <-- name of the topic as configured in secura air, make different topic per value
      value_template: "{{value_json.value}}"
      unit_of_measurement: "ppm"

4. Goto Developer tools > states > search for the new entities. You should see the new values
5. troubleshooting. Goto devices > MQTT > configure
6. Listen to a topic > enter topic and just wait if message fly by.
